version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: dbeuser
  MYSQL_PASSWORD: dbpassword
  MYSQL_DATABASE: blogdb
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3316:3316
    restart: unless-stopped
    volumes:
      - ./db/blog.sql:/docker-entrypoint-initdb.d/blog.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
      DB_HOST: mysql
      DB_ENGING: mysql
      DB_USERNAME: dbeuser
      DB_PASSWORD: dbpassword
      DB_NAME: blogdb
      PORT: 8000
      JWT_TOKEN: react_docker_node
      PASSWORD_SALT: react_docker_node
      APITOKEN: YgP02dsdsd4ksdsdsdsdg79PYgA2N06eMRuP0YdT9civRD7BRZuZRZqSCQhZMepLDmss
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm run dev
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start